# Use the official Python base image
FROM pytorch/pytorch:1.9.0-cuda10.2-cudnn7-runtime
# Set the working directory inside the container
WORKDIR /app

# Copy the requirements.txt file to the working directory
COPY requirements.txt .

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code to the working directory
COPY . .

# Expose the port on which the Flask application will run
EXPOSE 5000

# Set the entrypoint command to run the Flask application
CMD ["python", "app.py"]
