name: simulate tests
on:
  [workflow_dispatch]
jobs:
  deployment:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: flask-pytorch-backend-master/frontend 
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install deps
        run: npm install
      - name: Test app
        run: npm run test
      - name: Lint code
        run: npm run lint
      # - name: Build App
      #   run: npm run build
